services:
  database:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: movie_critics
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
