services:
  database:
    image: postgres:17-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: movie_critics
    volumes:
      - postgres-data:/var/lib/postgresql/data

  keycloak:
    build:
      context: ./keycloak
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - "9000:9000"
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KC_HOSTNAME: localhost
      KC_HTTP_PORT: 9000

volumes:
  postgres-data:
