services:
  database:
    image: postgres:17-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: movie_critics
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  keycloak:
    build:
      context: ./keycloak
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - "9000:9000"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HOSTNAME: localhost
      KC_HTTP_PORT: 9000
    volumes:
      - keycloak-data:/opt/keycloak/data

volumes:
  postgres-data:
  keycloak-data:
