spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/moviecritics
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    web: debug
    sql: debug
