spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/movie_critics
    username: postgres
    password: password

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9000/realms/movie-critics

      client:
        provider:
          keycloak:
            issuer-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}

        registration:
          keycloak:
            client-id: spring-boot-api
            client-secret: MKHz0Kw82cGhDIwmz3vZ8fO6AmY87eQn
            authorization-grant-type: authorization_code
            scope:
              - openid

logging:
  level:
    web: debug
    sql: debug
