spring:
  application:
    name: movie_critics
  data:
    web:
      pageable:
        default-page-size: 20
        max-page-size: 50
  servlet:
    multipart:
      max-file-size: 5MB

springdoc:
  api-docs:
    path: /api/docs
  swagger-ui:
    path: /swagger-ui.html

server:
  compression:
    enabled: true
  error:
    include-message: always
    include-path: never
